### ISSUE TITLE
`curl api.kanye.rest` command stopped returning a quote on the terminal

### ISSUE THREAD

**Issue by erhanalankus** [ajzbc/kanye.rest#44]
I used to be able to type `curl api.kanye.rest` to a terminal and see a quote.
Now when I enter that command, I get no output on the terminal.

**Comment by erhanalankus** [comment]
Maybe we can add a newline character to the return body too.
Then it will look prettier, like this:
![Screen Shot 2022-09-14 at 12 08 31](https://user-images.githubusercontent.com/8477179/190112162-d4aa85a5-58dc-4661-b9d3-506935de42c8.png)

Instead of this:
![Screen Shot 2022-09-14 at 12 09 02](https://user-images.githubusercontent.com/8477179/190112330-abcb15da-c281-4232-b1d8-e6a123ed8acb.png)

**Comment by ajzbc** [comment]
Will adjust cloudflare settings to allow HTTP

In terms of the newline character I can look at adding that. How does [https://api.kanye.rest/text](https://api.kanye.rest/text) look?

**Comment by erhanalankus** [comment]
Hi @ajzbc ,
It looks nice, much cleaner :)
![image](https://user-images.githubusercontent.com/8477179/190826411-c9ced788-cfba-4d17-98c8-c528372ddfe6.png)
