### ISSUE TITLE
Made yet another simple page that uses your UI - gives you a new quote every 10 seconds :) 

### ISSUE THREAD

**Issue by brainburn** [ajzbc/kanye.rest#5]
let me know if you don't want to handle the server load from that - https://github.com/brainburn/kanye_quotes

Awesome idea :)

**Comment by ajzbc** [comment]
I would appreciate a lower frequency.
I need to make some changes to the API to cache the quotes every day instead of reading the database every time. Once I work that out I will let you know and you can go crazy with it!

**Comment by brainburn** [comment]
aight! :) i will keep track of the repo. I think it will be really awesome if we made a bunch of bots just throwing quotes at each other. lmk if i can help you with any coding

**Comment by ajzbc** [comment]
Thanks! I have finals this week so I don't have time to implement caching anytime soon. If you could help on that it would be awesome!
