### ISSUE TITLE
Made an extension using your api

### ISSUE THREAD

**Issue by ivanlebanov** [ajzbc/kanye.rest#7]
https://chrome.google.com/webstore/detail/kanye-west-says/jldfgabobeklpdaofhhppkniokfckije- thanks for the brilliant service you've developed

**Comment by ajzbc** [comment]
Broken link?

**Comment by ivanlebanov** [comment]
https://chrome.google.com/webstore/detail/kanye-west-says/jldfgabobeklpdaofhhppkniokfckije/
